#!/bin/bash

if [ -z "$1" ]; then
  echo "Error: You must pass a version"
  echo ""
  npm version -h
  exit 1
fi

now=$(date +%s)
stash_name="pre-version-$now"
current_branch=$(git branch --show-current)
branch_name="version-$now"

# Get a clean env
git stash save -q --keep-index $stash_name
git checkout -q origin/master
git checkout -q -b $branch_name

# Build docs
npm run storybook:build

git add -A .

# Bump version
npm version $1
pkg_version=$(node -p -e "require('./package.json').version")

git push -u origin "release/$pkg_version"

git checkout $current_branch

stashes=$(git stash list)
if [[ $stashes == "$stash_name" ]]; then
  git stash pop -q
fi