name: Add issue to project

on:
  issues:
    types: [ milestoned ]

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.2
        if: contains(github.event.issue.milestone.title, 'v1.0')
        with:
          project: Kanban
          column: To Do
          repo-token: ${{ github.token }}
